### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by spikehidden** [funniray/minimap-control#2]
The latest version (1.5.0) seems to not recognize Xaero's Minimap nor Journeymap and always only sends the config for Voxel which causes Journeymap to act like there is no Server-side compatibility and Xaero's Minimap to act like all features shall be disabled.

If you need anymore info, let me know.

**Comment by funniray** [comment]
can you tell me what game version you were using (client and server), what version of journeymap and what version of xaero's you tested? Additionally, are you using a proxy server like velocity or bungeecord?

**Comment by spikehidden** [comment]
## Setup
I've listed all versions I have tried and also did NOT have Journeymap and Xaero's Map Mods installed at the same time.
### My Server
| Server | Proxy | Xaero Minimap | Xaero Worldmap | Journeymap | Fabric Loader | Client |
| :----- | :---: | :-----------: | :------------: | :--------: | :----: | :----: |
| git-Purpur-2139 (MC: 1.20.4) | Bungeecord | 23.9.7; 23.9.6 | 1.37.8; 1.37.7; 1.37.6 | 1.20.4-5.9.20-fabric | 0.15.6 | 1.20.4 |

### Test Server
To check if it might be an incompatibility with the proxy or another Plugin I did setup a local test server with this config

| Server | Proxy | Xaero Minimap | Xaero Worldmap | Journeymap | Fabric Loader | Client |
| :----- | :---: | :-----------: | :------------: | :--------: | :----: | :----: |
| git-Paper-424 (MC: 1.20.4) | none | 23.9.7; 23.9.6 | 1.37.8; 1.37.7; 1.37.6 | 1.20.4-5.9.20-fabric | 0.15.6 | 1.20.4 |

And by the way in the meantime I also tried version 1.4.0 which didn't work as well.

**Comment by funniray** [comment]
I completely forgot to ask about the config file you used. The plugin defaults to allowing everything, as this is the default behavior of the mods themselves.

additionally, does the journeymap server admin tab work, or does it claim "journeymap isn't installed on the server"?

**Comment by spikehidden** [comment]
It says Journeymap isn't installed on the server and so the admin tab isn't working as well.

Config file will be following later today.

**Comment by spikehidden** [comment]
Sorry for the delay but here's my config:

<details>
<summary>config.yml</summary>

```yaml
global-journeymap-config: {journeymap-enabled: 'true', use-world-id: 'true', view-only-server-properties: 'false',
    allow-multiplayer-settings: Op, world-player-radar: Op, world-player-radar-update-time: '5',
    see-underground-players: Op, hide-ops: 'false', hide-spectators: 'true', allow-death-points: 'true',
    show-in-game-beacons: 'true', allow-waypoints: 'true', teleport-enabled: 'false',
    render-range: '10', surface-mapping: ALL, topo-mapping: ALL, biome-mapping: ALL,
    cave-mapping: Op, radar-enabled: Op, player-radar-enabled: 'true', villager-radar-enabled: 'true',
    animal-radar-enabled: 'true', mob-radar-enabled: 'true', config-version: 5.9.15}
global-xaeros-config: {enabled: true, cave-mode: false, nether-cave-mode: true, radar: true}
global-voxel-config: {enabled: false, radar-allowed: false, radar-mobs-allowed: false,
    radar-players-allowed: false, caves-allowed: false, teleport-command: tp %p %x
        %y %z}
default-world-config: {enabled: 'false', teleport-enabled: 'false', render-range: '0',
    surface-mapping: ALL, topo-mapping: ALL, biome-mapping: ALL, cave-mapping: Op,
    radar-enabled: Op, player-radar-enabled: 'true', villager-radar-enabled: 'true',
    animal-radar-enabled: 'true', mob-radar-enabled: 'true', config-version: 5.9.15}
worlds:
    world:
        world-id: e16c48ec-67af-4234-a969-c17dbccdb7fd
        journeymap-config: {enabled: 'false', teleport-enabled: 'false', render-range: '0',
            surface-mapping: ALL, topo-mapping: ALL, biome-mapping: ALL, cave-mapping: ALL,
            radar-enabled: ALL, player-radar-enabled: 'true', villager-radar-enabled: 'true',
            animal-radar-enabled: 'true', mob-radar-enabled: 'true', config-version: 5.9.15}
        xaeros-config: {enabled: true, cave-mode: false, nether-cave-mode: true, radar: false}
        voxel-config: {enabled: false, radar-allowed: true, radar-mobs-allowed: true,
            radar-players-allowed: true, caves-allowed: true, teleport-command: tp
                %p %x %y %z}
    world_nether:
        world-id: da5de754-6bde-4eb2-af77-d17ee471a1bf
        journeymap-config: {enabled: 'true', teleport-enabled: 'false', render-range: '0',
            surface-mapping: ALL, topo-mapping: ALL, biome-mapping: ALL, cave-mapping: ALL,
            radar-enabled: Op, player-radar-enabled: 'true', villager-radar-enabled: 'true',
            animal-radar-enabled: 'true', mob-radar-enabled: 'true', config-version: 5.9.15}
        xaeros-config: {enabled: true, cave-mode: false, nether-cave-mode: true, radar: true}
        voxel-config: {enabled: true, radar-allowed: false, radar-mobs-allowed: false,
            radar-players-allowed: false, caves-allowed: true, teleport-command: tp
                %p %x %y %z}
    farm_nether:
        world-id: a0f7eca9-8238-490e-b32b-e2863b13664d
        journeymap-config: {enabled: 'true', teleport-enabled: 'false', render-range: '0',
            surface-mapping: ALL, topo-mapping: ALL, biome-mapping: ALL, cave-mapping: ALL,
            radar-enabled: ALL, player-radar-enabled: 'true', villager-radar-enabled: 'true',
            animal-radar-enabled: 'true', mob-radar-enabled: 'true', config-version: 5.9.15}
        xaeros-config: {enabled: true, cave-mode: true, nether-cave-mode: true, radar: true}
        voxel-config: {enabled: true, radar-allowed: true, radar-mobs-allowed: true,
            radar-players-allowed: true, caves-allowed: true, teleport-command: tp
                %p %x %y %z}
    farm:
        world-id: b45ae230-7796-43f1-bada-00bd693cb60d
        journeymap-config: {enabled: 'true', teleport-enabled: 'false', render-range: '0',
            surface-mapping: ALL, topo-mapping: ALL, biome-mapping: ALL, cave-mapping: ALL,
            radar-enabled: ALL, player-radar-enabled: 'true', villager-radar-enabled: 'true',
            animal-radar-enabled: 'true', mob-radar-enabled: 'true', config-version: 5.9.15}
        xaeros-config: {enabled: true, cave-mode: true, nether-cave-mode: true, radar: true}
        voxel-config: {enabled: true, radar-allowed: true, radar-mobs-allowed: true,
            radar-players-allowed: true, caves-allowed: true, teleport-command: tp
                %p %x %y %z, cave-mode: true, nether-cave-mode: true, radar: false}
```

</details>
